// templates/solidjs-ts/src/pages/About.tsx
import { Component } from 'solid-js'

const About: Component = () => {
  return (
    <div class="about">
      <h1>About Page</h1>
      <p>This is a TypeScript SolidJS application created with YBM CLI.</p>
      <p>
        It includes SolidJS Router for navigation, TypeScript for type safety,
        and Vite for fast development and optimized builds.
      </p>
    </div>
  )
}

export default About

// templates/react-ts/src/pages/About.tsx
import React from 'react'

const About: React.FC = () => {
  return (
    <div className="about">
      <h1>About Page</h1>
      <p>This is a TypeScript React application created with YBM CLI.</p>
      <p>
        It includes React Router for navigation, TypeScript for type safety,
        and Vite for fast development and optimized builds.
      </p>
    </div>
  )
}

export default About
