// templates/solidjs-ts/src/pages/Home.tsx
import { Component } from 'solid-js'
import Counter from '../components/Counter'

interface HomeProps {
  count: number;
  setCount: (value: number | ((prev: number) => number)) => void;
}

const Home: Component<HomeProps> = (props) => {
  return (
    <div class="home">
      <h1>Home Page</h1>
      <p>Welcome to the SolidJS + TypeScript template!</p>
      <Counter count={props.count} setCount={props.setCount} />
    </div>
  )
}

export default Home

// templates/react-ts/src/pages/Home.tsx
import React from 'react'
import Counter from '../components/Counter'

interface HomeProps {
  count: number;
  setCount: React.Dispatch<React.SetStateAction<number>>;
}

const Home: React.FC<HomeProps> = ({ count, setCount }) => {
  return (
    <div className="home">
      <h1>Home Page</h1>
      <p>Welcome to the React + TypeScript template!</p>
      <Counter count={count} setCount={setCount} />
    </div>
  )
}

export default Home
