// templates/react-ts/src/pages/About.tsx
import React from 'react'

const About: React.FC = () => {
  return (
    <div className="about">
      <h1>About Page</h1>
      <p>This is a TypeScript React application created with YBM CLI.</p>
      <p>
        It includes React Router for navigation, TypeScript for type safety,
        and Vite for fast development and optimized builds.
      </p>
    </div>
  )
}

export default About

// templates/svelte-ts/src/pages/About.svelte
<script lang="ts">
  // TypeScript component
</script>

<main>
  <h1>About</h1>
  <p>This is a TypeScript Svelte application created with YBM CLI.</p>
  <p>
    It includes Svelte Navigator for routing, TypeScript for type safety,
    and Vite for fast development and optimized builds.
  </p>
</main>

<style>
  main {
    text-align: center;
    padding: 1em;
    max-width: 240px;
    margin: 0 auto;
  }

  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4em;
    font-weight: 100;
  }

  @media (min-width: 640px) {
    main {
      max-width: none;
    }
  }
</style>
