// templates/react-ts/src/components/Counter.tsx
import React from 'react'

interface CounterProps {
  count: number;
  setCount: React.Dispatch<React.SetStateAction<number>>;
}

const Counter: React.FC<CounterProps> = ({ count, setCount }) => {
  const increment = (): void => {
    setCount(prevCount => prevCount + 1)
  }

  const decrement = (): void => {
    setCount(prevCount => prevCount - 1)
  }

  return (
    <div className="counter">
      <h2>Counter: {count}</h2>
      <div className="counter-buttons">
        <button onClick={decrement}>-</button>
        <button onClick={increment}>+</button>
      </div>
    </div>
  )
}

export default Counter

// templates/solidjs-ts/src/components/Counter.tsx
import { Component } from 'solid-js'

interface CounterProps {
  count: number;
  setCount: (value: number | ((prev: number) => number)) => void;
}

const Counter: Component<CounterProps> = (props) => {
  const increment = () => {
    props.setCount(prev => prev + 1)
  }

  const decrement = () => {
    props.setCount(prev => prev - 1)
  }

  return (
    <div class="counter">
      <h2>Counter: {props.count}</h2>
      <div class="counter-buttons">
        <button onClick={decrement}>-</button>
        <button onClick={increment}>+</button>
      </div>
    </div>
  )
}

export default Counter
